---
- name: install default packages
  become: true
  apt: name={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - ruby2.1-dev
    - build-essential
  tags: sass

- name: install sass
  become: true
  gem: name={{ item.name }} state=present user_install=no
  with_items:
    - { name: sass }
    - { name: sass-globbing }
    - { name: compass }
    - { name: compass-normalize }
  tags: sass
