- name: install default packages
  become: true
  apt: name={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - php5-fpm
    - php5-common
    - php5-curl
    #- php5-intl
    - php5-json
    #- php5-gd
    #- php5-imagick
    #- php5-imap
    #- php5-memcache
    #- php5-memcached
    - php5-mcrypt
    - php5-mysql
    #- php5-recode
    #- php5-snmp
    - php5-sqlite
    - php5-tidy
    #- php5-xcache
    - php5-xdebug
    - php5-xmlrpc
    - php5-opcache
    #- php5-xsl
    #- php-pear
    #- php-auth
  notify:
    - restart php5-fpm service
  tags: php5-fpm

- name: backup default config
  become: true
  include: ../../_helper/backup.yml
  vars: { file: /etc/php5/fpm/pool.d/www.conf, delete: false }
  tags: php5-fpm

- name: configure fcgi
  become: true
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="listen =.*" line="listen = 127.0.0.1:9000" state=present backrefs=yes
  notify:
    - restart php5-fpm service
  tags: php5-fpm

- name: configure user
  become: true
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="user =.*" line="user = {{ ansible_user }}" state=present backrefs=yes
  notify:
    - restart php5-fpm service
  tags: php5-fpm

- name: configure group
  become: true
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf regexp="group =.*" line="group = {{ ansible_user }}" state=present backrefs=yes
  notify:
    - restart php5-fpm service
  tags: php5-fpm

- name: check service state
  become: true
  service: name=php5-fpm state=started enabled=yes
  tags: php5-fpm
