---
- name: install packages
  become: true
  apt: name={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - apache2-mpm-worker
    - apache2-doc
  tags: apache2

- name: enable modules
  become: true
  apache2_module: name='{{ item }}' state=present
  with_items:
    - expires
    - headers
    - rewrite
    - proxy_fcgi
    - vhost_alias
  notify:
    - restart apache2 service
  tags: apache2

- name: backup port config
  become: true
  include: ../../_helper/backup.yml
  vars: { file: /etc/apache2/ports.conf, delete: false }
  tags: apache2

- name: disable default port
  become: true
  lineinfile: dest=/etc/apache2/ports.conf regexp="Listen 80" line="#Listen 80" state=present backrefs=yes
  notify:
    - restart apache2 service
  tags: apache2

- name: check service state
  become: true
  service: name=apache2 state=started enabled=yes
  tags: apache2
