---
- name: install default packages
  become: true
  apt: name={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - mysql-server
    - mysql-client
  notify:
    - restart mysql service
  tags: mysql

- name: lookup mysql user
  shell: mysql -u root -sN -e "SELECT COUNT(*) FROM mysql.user WHERE User = '{{ ansible_user }}';"
  register: mysql_user
  changed_when: mysql_user.stdout|int != 1
  tags: mysql

- name: create mysql user
  shell: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '{{ ansible_user }}'@'%' REQUIRE NONE WITH GRANT OPTION;"
  when: mysql_user.changed
  tags: mysql

- name: check mysql service state
  become: true
  service: name=mysql state=started enabled=yes
  tags: mysql
