---
- name: install default packages
  become: true
  apt: name={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - ruby2.1
    - build-essential
  tags: capistrano

- name: install capistrano
  become: true
  gem: name={{ item.name }} version={{ item.version }} state=present user_install=no
  with_items:
    - { name: capistrano, version: 2.15.9 }
    - { name: railsless-deploy, version: 1.1.3 }
    - { name: capistrano_rsync_with_remote_cache, version: 2.4.0 }
    - { name: net-ssh, version: 3.2.0 }
  tags: capistrano

- name: remove unwanted packages
  become: true
  gem: name={{ item.name }} version={{ item.version }} state=absent user_install=no
  with_items:
    - { name: net-ssh, version: 4.0.0.beta3 }
  tags: capistrano
