---
- name: add apt-key
  become: true
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  tags: nginx

- name: adding sources
  become: true
  apt_repository: repo="deb http://nginx.org/packages/mainline/debian/ jessie nginx" state=present update_cache=yes
  tags: nginx

- name: install default packages
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - nginx
  notify:
    - restart nginx service
  tags: nginx

- name: backup and remove nginx default vhost
  become: true
  include: ../../_helper/backup.yml
  vars: { file: /etc/nginx/conf.d/default.conf, delete: true }
  tags: nginx

- name: backup nginx config
  become: true
  include: ../../_helper/backup.yml
  vars: { file: /etc/nginx/nginx.conf, delete: false }
  tags: nginx

- name: configure nginx user
  become: true
  lineinfile: dest=/etc/nginx/nginx.conf regexp="user.*nginx;" line="user {{ ansible_user }} {{ ansible_user }};" state=present backrefs=yes
  notify:
    - restart nginx service
  tags: nginx

- name: create and enable vhosts
  become: true
  template: src=nginx_vhost.conf dest=/etc/nginx/conf.d/{{ item.key }}.conf
  vars:
    port: "{{ item.value.http }}"
    fcgi: "{{ item.value.fcgi }}"
  with_dict: "{{ nginx_vhosts }}"
  notify:
    - restart nginx service
  tags:
    - nginx
    - vhosts

- name: check nginx service state
  become: true
  service: name=nginx state=started enabled=yes
  tags: nginx
