---
- name: add apt-key
  become: true
  apt_key: url=https://www.mongodb.org/static/pgp/server-3.2.asc state=present
  tags: mongodb

- name: add repository
  become: true
  apt_repository: repo="deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main" state=present update_cache=yes
  tags: mongodb

- name: install default packages
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - mongodb-org
  notify:
    - restart mongodb service
  tags: mongodb

- name: check mongodb service state
  become: true
  service: name=mongod state=started enabled=yes
  tags: mongodb
