---
- name: install default packages
  become: true
  apt: name={{ item }} state=latest update_cache=true cache_valid_time=3600
  with_items:
    - apache2-mpm-worker
    - apache2-doc
  notify:
    - restart apache2 service
  tags: apache2

- name: enable modules
  become: true
  apache2_module: name='{{ item }}' state=present
  with_items:
    - ssl
    - expires
    - headers
    - rewrite
    - proxy_fcgi
    - vhost_alias
  notify:
    - restart apache2 service
  tags: apache2

- name: disable default vhosts
  become: true
  shell: a2dissite {{ item }}.conf removes=/etc/apache2/sites-enabled/{{ item }}.conf
  with_items:
    - 000-default
    - default-ssl
  notify:
    - restart apache2 service
  tags: apache2_rem

- name: create vhosts
  become: true
  template: src=apache2_vhost.conf dest=/etc/apache2/sites-available/{{ item.name }}.conf
  vars:
    port: "{{ item.http }}"
    fcgi: "{{ item.fcgi }}"
  with_items: "{{ apache2_vhosts }}"
  notify:
    - restart apache2 service
  tags:
    - apache2
    - vhosts

- name: enable vhosts
  become: true
  shell: a2ensite {{ item.name }} creates=/etc/apache2/sites-enabled/{{ item.name }}.conf
  with_items: "{{ apache2_vhosts }}"
  notify:
    - restart apache2 service
  tags:
    - apache2
    - vhosts

- name: create ssl vhosts
  become: true
  template: src=apache2_vhost-ssl.conf dest=/etc/apache2/sites-available/{{ item.name }}-ssl.conf
  vars:
    port: "{{ item.https }}"
    fcgi: "{{ item.fcgi }}"
  with_items: "{{ apache2_vhosts }}"
  notify:
    - restart apache2 service
  tags:
    - apache2
    - vhosts

- name: enable ssl vhosts
  become: true
  shell: a2ensite {{ item.name }}-ssl creates=/etc/apache2/sites-enabled/{{ item.name }}-ssl.conf
  with_items: "{{ apache2_vhosts }}"
  notify:
    - restart apache2 service
  tags:
    - apache2
    - vhosts

- name: check service state
  become: true
  service: name=apache2 state=started enabled=yes
  tags: apache2
