---
- name: create php-fpm vhost
  become: true
  template: src=apache2_vhost.conf dest=/etc/apache2/sites-available/fpm.conf
  vars: { port: "{{ fpm_port }}", fcgi: 9000 }
  when: fpm_port is defined and fpm_port|int >= 1
  notify:
    - restart apache2 service
  tags: apache2_vhost

- name: enable php-fpm vhost
  become: true
  shell: a2ensite fpm creates=/etc/apache2/sites-enabled/fpm.conf
  when: fpm_port is defined and fpm_port|int >= 1
  notify:
    - restart apache2 service
  tags: apache2_vhost

- name: create hhvm vhost
  become: true
  template: src=apache2_vhost.conf dest=/etc/apache2/sites-available/hhvm.conf
  vars: { port: "{{ hhvm_port }}", fcgi: 9001 }
  when: hhvm_port is defined and hhvm_port|int >= 1
  notify:
    - restart apache2 service
  tags: apache2_vhost

- name: enable hhvm vhost
  become: true
  shell: a2ensite hhvm creates=/etc/apache2/sites-enabled/hhvm.conf
  when: hhvm_port is defined and hhvm_port|int >= 1
  notify:
    - restart apache2 service
  tags: apache2_vhost
