---
- name: add apt-key
  become: true
  apt_key: url=http://dl.hhvm.com/conf/hhvm.gpg.key state=present
  tags: hhvm

- name: add repository
  become: true
  apt_repository: repo="deb http://dl.hhvm.com/debian jessie main" state=present update_cache=yes
  tags: hhvm

- name: install default packages
  become: true
  apt: name={{ item }} state=latest
  with_items:
    - hhvm
  notify:
    - restart hhvm service
  tags: hhvm

- name: configure fcgi
  become: true
  ini_file: dest=/etc/hhvm/server.ini section="" option="hhvm.server.port" value="{{ port }}"
  notify:
    - restart hhvm service
  tags: hhvm

- name: check hhvm service state
  become: true
  service: name=hhvm state=started enabled=yes
  tags: hhvm
