---
- name: create workspace structure
  file: path=/home/{{ ansible_user }}/workspace/admin/db state=directory
  tags: phpmyadmin

- name: download package
  unarchive: src=https://files.phpmyadmin.net/phpMyAdmin/{{ pma_version }}/phpMyAdmin-{{ pma_version }}-{{ pma_language }}.tar.gz dest=/home/{{ ansible_user }}/workspace/admin/db copy=no
  tags: phpmyadmin

- name: link to htdocs
  file: src=/home/{{ ansible_user }}/workspace/admin/db/phpMyAdmin-{{ pma_version }}-{{ pma_language }} dest=/home/{{ ansible_user }}/workspace/admin/db/htdocs state=link
  tags: phpmyadmin

- name: lookup config
  stat: path=/home/{{ ansible_user }}/workspace/admin/db/htdocs/config.inc.php
  register: config_inc_php
  tags: phpmyadmin

- name: create config
  copy: remote_src=yes src=/home/{{ ansible_user }}/workspace/admin/db/htdocs/config.sample.inc.php dest=/home/{{ ansible_user }}/workspace/admin/db/htdocs/config.inc.php
  when: config_inc_php.stat.exists == false
  tags: phpmyadmin

- name: import database-structure and -tables
  shell: mysql < /home/{{ ansible_user }}/workspace/admin/db/htdocs/sql/create_tables.sql
  failed_when: false
  changed_when: false
  tags: phpmyadmin

- name: config blowfish_secret
  lineinfile: dest=/home/{{ ansible_user }}/workspace/admin/db/htdocs/config.inc.php regexp="\$cfg\[\'blowfish_secret\'\] =.*" line="$cfg['blowfish_secret'] = '{{ ansible_user }}';" state=present backrefs=yes
  tags: phpmyadmin

- name: config host
  lineinfile: dest=/home/{{ ansible_user }}/workspace/admin/db/htdocs/config.inc.php regexp="\$cfg\[\'Servers\'\]\[\$i\]\[\'host\'\] =.*" line="$cfg['Servers'][$i]['host'] = '127.0.0.1';" state=present backrefs=yes
  tags: phpmyadmin

- name: config nopassword
  lineinfile: dest=/home/{{ ansible_user }}/workspace/admin/db/htdocs/config.inc.php regexp="\$cfg\[\'Servers\'\]\[\$i\]\[\'AllowNoPassword\'\] =.*" line="$cfg['Servers'][$i]['AllowNoPassword'] = 'true';" state=present backrefs=yes
  tags: phpmyadmin
